# Generated by Django 5.2.10 on 2026-03-17 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dietary", models.JSONField(blank=True, default=list)),
                ("max_price", models.PositiveSmallIntegerField(default=4)),
                ("min_rating", models.FloatField(default=0.0)),
                (
                    "adventurousness",
                    models.CharField(default="Balanced", max_length=32),
                ),
                ("price_bias", models.FloatField(default=5.0)),
                ("cuisines", models.JSONField(blank=True, default=dict)),
                ("liked_places", models.JSONField(blank=True, default=list)),
                ("disliked_places", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
