# Generated by Django 6.0.2 on 2026-03-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary', models.JSONField(blank=True, default=list)),
                ('max_price', models.PositiveSmallIntegerField(default=4)),
                ('min_rating', models.PositiveSmallIntegerField(default=0)),
                ('adventurousness', models.CharField(default='Balanced', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
