# Generated by Django 6.0.2 on 2026-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cuisines',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='price_bias',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='min_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
