# Generated by Django 5.2.10 on 2026-03-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="top_searches",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
